services:
  - type: web
    name: translator-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: development
    plan: free
    autoDeploy: true
